ingress:
  host: dev.brightstaraid.org
  # certificateArn injected at deploy time via --set ingress.certificateArn=...

configmap:
  frontendOrigin: "https://dev.brightstaraid.org"

# Dev uses -dev ECR repositories and a single replica per service to reduce cost.
frontend:
  replicas: 1
  image:
    repository: 399839753928.dkr.ecr.eu-west-1.amazonaws.com/techbleat/frontend-dev

userService:
  replicas: 1
  image:
    repository: 399839753928.dkr.ecr.eu-west-1.amazonaws.com/techbleat/user-service-dev

transactionService:
  replicas: 1
  image:
    repository: 399839753928.dkr.ecr.eu-west-1.amazonaws.com/techbleat/transaction-service-dev

activityService:
  replicas: 1
  image:
    repository: 399839753928.dkr.ecr.eu-west-1.amazonaws.com/techbleat/activity-service-dev

externalSecrets:
  awsSecretKey: banking/db-credentials-dev
