apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
  namespace: {{ .Release.Namespace }}
data:
  DATABASE_URL: {{ .Values.configmap.databaseUrl | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.configmap.springDatasourceUrl | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.configmap.kafkaBootstrapServers | quote }}
  REDIS_HOST: {{ .Values.configmap.redisHost | quote }}
  REDIS_PORT: {{ .Values.configmap.redisPort | quote }}
  FRONTEND_ORIGIN: {{ .Values.configmap.frontendOrigin | quote }}
