apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done"]
        - name: wait-for-kafka
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z kafka-service 9092; do echo waiting for kafka; sleep 2; done"]
      containers:
        - name: activity-service
          image: 399839753928.dkr.ecr.eu-west-1.amazonaws.com/techbleat/activity-service:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: banking-config
                  key: DATABASE_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: banking-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: FRONTEND_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: banking-config
                  key: FRONTEND_ORIGIN
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: banking
spec:
  selector:
    app: activity-service
  ports:
    - port: 8001
